/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module muxrightsign_23 (
    input [3:0] b,
    input [15:0] a,
    output reg [15:0] x
  );
  
  
  
  always @* begin
    x[0+15-:16] = $signed(a[0+15-:16]) >>> b;
  end
endmodule
