/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module birdPosition_17 (
    input clk,
    input rst,
    input btn,
    output reg [7:0] outPosition
  );
  
  
  
  wire [16-1:0] M_alu_out;
  wire [1-1:0] M_alu_overflow;
  reg [16-1:0] M_alu_a;
  reg [16-1:0] M_alu_b;
  reg [6-1:0] M_alu_alufn;
  alu_3 alu (
    .a(M_alu_a),
    .b(M_alu_b),
    .alufn(M_alu_alufn),
    .out(M_alu_out),
    .overflow(M_alu_overflow)
  );
  
  reg [7:0] M_position_d, M_position_q = 8'h10;
  
  always @* begin
    M_position_d = M_position_q;
    
    M_alu_a = M_position_q;
    M_alu_b = 1'h1;
    outPosition = M_position_q;
    if (btn == 1'h1) begin
      M_alu_alufn = 17'h186a0;
      M_position_d = M_alu_out;
    end else begin
      M_alu_alufn = 17'h186a1;
      M_position_d = M_alu_out;
    end
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_position_q <= 8'h10;
    end else begin
      M_position_q <= M_position_d;
    end
  end
  
endmodule
