/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module boolean_14 (
    input [3:0] alufn30,
    input [15:0] a,
    input [15:0] b,
    output reg [15:0] out
  );
  
  
  
  integer i;
  
  always @* begin
    out = 1'h0;
    if (alufn30 == 7'h64) begin
      out = a & b;
    end
    if (alufn30 == 11'h456) begin
      out = a ^ b;
    end
    if (alufn30 == 1'h1) begin
      out = ~a ^ b;
    end
    if (alufn30 == 7'h6f) begin
      out = ~a & b;
    end
    if (alufn30 == 10'h3f2) begin
      out = a;
    end
  end
endmodule
