/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module pattern_9 (
    input clk,
    input rst,
    input clk2,
    input rst2,
    input button,
    output reg out,
    output reg [63:0] outred,
    output reg [63:0] outblue,
    output reg [63:0] outgreen
  );
  
  
  
  wire [8-1:0] M_b_outPosition;
  reg [1-1:0] M_b_clk;
  reg [1-1:0] M_b_rst;
  reg [1-1:0] M_b_btn;
  birdPosition_17 b (
    .clk(M_b_clk),
    .rst(M_b_rst),
    .btn(M_b_btn),
    .outPosition(M_b_outPosition)
  );
  
  wire [8-1:0] M_p_out0;
  wire [8-1:0] M_p_out1;
  wire [8-1:0] M_p_out2;
  wire [8-1:0] M_p_out3;
  wire [8-1:0] M_p_out4;
  wire [8-1:0] M_p_out5;
  wire [8-1:0] M_p_out6;
  wire [8-1:0] M_p_out7;
  wire [8-1:0] M_p_out8;
  wire [8-1:0] M_p_out9;
  wire [8-1:0] M_p_out10;
  wire [8-1:0] M_p_out11;
  wire [8-1:0] M_p_out12;
  wire [8-1:0] M_p_out13;
  wire [8-1:0] M_p_out14;
  wire [8-1:0] M_p_out15;
  reg [1-1:0] M_p_clk;
  reg [1-1:0] M_p_rst;
  reg [1-1:0] M_p_btn;
  pillarShift_18 p (
    .clk(M_p_clk),
    .rst(M_p_rst),
    .btn(M_p_btn),
    .out0(M_p_out0),
    .out1(M_p_out1),
    .out2(M_p_out2),
    .out3(M_p_out3),
    .out4(M_p_out4),
    .out5(M_p_out5),
    .out6(M_p_out6),
    .out7(M_p_out7),
    .out8(M_p_out8),
    .out9(M_p_out9),
    .out10(M_p_out10),
    .out11(M_p_out11),
    .out12(M_p_out12),
    .out13(M_p_out13),
    .out14(M_p_out14),
    .out15(M_p_out15)
  );
  
  always @* begin
    M_b_btn = button;
    M_b_clk = clk2;
    M_b_rst = rst2;
    M_p_clk = clk2;
    M_p_rst = rst2;
    M_p_btn = button;
    out = 1'h0;
    outred = {8'h00, 8'h00, M_b_outPosition, 8'h00, 8'h00, 8'h00, 8'h00, 8'h00};
    outblue = {M_p_out0, M_p_out1, M_p_out2, M_p_out3, M_p_out4, M_p_out5, M_p_out6, M_p_out7};
    outgreen = 64'h0000000000000000;
  end
endmodule
